package com.rftg.toad;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/languages") // This means URL's start with /demo (after Application path)
public class LanguageController {
  @Autowired // This means to get the bean called LanguageRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private LanguageRepository languageRepository;

  @PostMapping(path = "/add") // Map ONLY POST Requests
  public @ResponseBody String addNewLanguage(@RequestParam Integer language_id, @RequestParam String name,
      @RequestParam String last_name, @RequestParam String last_update) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Language n = new Language();
    n.setName(name);
    n.setLast_update(last_update);
    languageRepository.save(n);
    return "Saved";
  }

  @GetMapping()
  public @ResponseBody Iterable<Language> getAllLanguages() {
    // This returns a JSON or XML with the Languages
    return languageRepository.findAll();
  }

  /**
   * @param language_id
   * @return
   */



}