package com.rftg.toad;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/staff")
public class StaffController {
  @Autowired // This means to get the bean called FilmRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private StaffRepository staffRepository;

  @GetMapping()
   public @ResponseBody Iterable<Staff> getAllStaff() {
    // This returns a JSON or XML with the Films
    System.out.println("Serveur connecté");
    return staffRepository.findAll();
  }

}
